language: elixir
matrix:
  include:
    - otp_release: 20.1
      elixir: 1.6
env:
  global:
    - MIX_HOME=$HOME/.mix
cache:
  directories:
  - $HOME/.mix
  - deps
  - _build
script:
  - mix docs
  - mix test
  - mix format --check-formatted
  - mix dialyzer
